name: bubble_tab_indicator
description: A Flutter library to add bubble-like effect to tab indicator to TabBar.
version: 0.1.5
author: Vipul Asri <vipulasri.2007@gmail.com>
homepage: https://github.com/vipulasri/flutter_bubble_tab_indicator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
